Repository pagopa/pn-frontend, pull requests merged in 2025-07, with the labels that each got.

#1562 Fix: Fix toast layout
  packages/pn-commons/src/components/CopyToClipboard.tsx
  packages/pn-commons/src/components/SnackBar/SnackBar.tsx
  packages/pn-pa-webapp/src/components/NewApiKey/__test__/SyncFeedbackApiKey.test.tsx
Labels: Q3.A

#1563 chore: change copy for some errors
  packages/pn-commons/src/utility/AppError/GenericAppError/InternalServerAppError.ts
  packages/pn-commons/src/utility/AppError/GenericAppError/UnhandledAppError.ts
  packages/pn-commons/src/utility/AppError/GenericAppError/__test__/InternalServerAppError.test.ts
  packages/pn-commons/src/utility/AppError/GenericAppError/__test__/UnhandledAppError.test.ts
  packages/pn-commons/src/utility/AppError/UnknownAppError.ts
  packages/pn-commons/src/utility/AppError/__test__/UnknownAppError.test.ts
  packages/pn-pa-webapp/public/locales/it/common.json
  packages/pn-pa-webapp/public/locales/it/notifiche.json
  packages/pn-personafisica-webapp/public/locales/it/common.json
  packages/pn-personafisica-webapp/public/locales/it/notifiche.json
  packages/pn-personagiuridica-webapp/public/locales/it/common.json
  packages/pn-personagiuridica-webapp/public/locales/it/notifiche.json
Labels: Q3.A

#1569 chore(pn-15279): change copy for notification fee options
  packages/pn-pa-webapp/public/locales/it/notifiche.json
Labels: Q3.A

#1565 fix(pn-15230): move DeliveryMandateNotFoundAppError translation to 'common' ns
  packages/pn-personafisica-webapp/public/locales/it/common.json
  packages/pn-personafisica-webapp/public/locales/it/deleghe.json
  packages/pn-personafisica-webapp/src/utility/AppError/DeliveryMandateNotFoundAppError.ts
  packages/pn-personafisica-webapp/src/utility/AppError/__test__/DeliveryMandateNotFoundAppError.test.ts
Labels: Q3.A

#1578 Feat/PN-15327: PF call api logout before redirect
  packages/pn-personafisica-webapp/src/App.tsx
  packages/pn-personafisica-webapp/src/__test__/App.test.tsx
  packages/pn-personafisica-webapp/src/api/auth/Auth.api.ts
  packages/pn-personafisica-webapp/src/api/auth/auth.routes.ts
  packages/pn-personafisica-webapp/src/redux/auth/actions.ts
Labels: Q3.A

#1577 feat/PN-15326: PG call api logout before redirect
  packages/pn-personagiuridica-webapp/src/App.tsx
  packages/pn-personagiuridica-webapp/src/__test__/App.test.tsx
  packages/pn-personagiuridica-webapp/src/api/auth/Auth.api.ts
  packages/pn-personagiuridica-webapp/src/api/auth/auth.routes.ts
  packages/pn-personagiuridica-webapp/src/redux/auth/actions.ts
Labels: Q3.A

#1586 refactor(pn-15400): add recap step for SERCQ activation wizard
  packages/pn-personafisica-webapp/public/locales/it/recapiti.json
  packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactActivation.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/SercqSendContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/__test__/SercqSendContactWizard.test.tsx
  packages/pn-personafisica-webapp/src/pages/DigitalContact.page.tsx
  packages/pn-personafisica-webapp/src/redux/contact/__test__/reducers.test.ts
  packages/pn-personafisica-webapp/src/redux/contact/reducers.ts
  packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
  packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactActivation.tsx
  packages/pn-personagiuridica-webapp/src/components/Contacts/SercqSendContactWizard.tsx
  packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
  packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/SercqSendContactWizard.test.tsx
  packages/pn-personagiuridica-webapp/src/pages/DigitalContact.page.tsx
  packages/pn-personagiuridica-webapp/src/redux/contact/__test__/reducers.test.ts
  packages/pn-personagiuridica-webapp/src/redux/contact/reducers.ts
Labels: TECH-FE-SERCQ-25

#1582 fix/PN-15404: update PEC activation flow
  packages/pn-personafisica-webapp/public/locales/it/recapiti.json
  packages/pn-personafisica-webapp/src/components/Contacts/PecContactWizard.tsx
  packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
  packages/pn-personagiuridica-webapp/src/components/Contacts/PecContactWizard.tsx
Labels: TECH-FE-SERCQ-25

#1589 fix/PN-15405: update copy
  packages/pn-personafisica-webapp/public/locales/it/recapiti.json
  packages/pn-personafisica-webapp/src/components/Contacts/IOContactWizard.tsx
  packages/pn-personagiuridica-webapp/public/locales/it/common.json
  packages/pn-personagiuridica-webapp/public/locales/it/recapiti.json
  packages/pn-personagiuridica-webapp/src/components/Contacts/DigitalContactActivation.tsx
  packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
Labels: TECH-FE-SERCQ-25

#1599 fix(pn-15729): add InformativeDialog for email during SERCQ activation wizard
  packages/pn-personafisica-webapp/src/components/Contacts/EmailSmsContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
  packages/pn-personagiuridica-webapp/src/components/Contacts/EmailSmsContactWizard.tsx
  packages/pn-personagiuridica-webapp/src/components/Contacts/__test__/DigitalContactActivation.test.tsx
Labels: Q3.A

#1593 TEST: fix test for logout API called
  packages/pn-pa-webapp/src/__test__/App.test.tsx
  packages/pn-personafisica-webapp/src/__test__/App.test.tsx
  packages/pn-personagiuridica-webapp/src/__test__/App.test.tsx
Labels: Q3.A

#1595 fix(PN-15402): track new events of SERCQ PEC
  packages/pn-commons/src/components/PnWizard/PnWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/DigitalContact.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/DigitalContactActivation.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/EmailSmsContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/HowItWorksContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/IOContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/PecContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/SercqSendContactWizard.tsx
  packages/pn-personafisica-webapp/src/components/Contacts/SmsContactItem.tsx
  packages/pn-personafisica-webapp/src/components/DomicileBanner/DomicileBanner.tsx
  packages/pn-personafisica-webapp/src/models/PFEventsType.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/PFEventStrategyFactory.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/KoErrorStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqPecStartActivationStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqSendAddEmailStartStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqSendAddSmsStartStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqSendEnterFlowStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqSendUxConversionStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqSendUxSuccessStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/SendAddSercqUxSuccessStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/UxConfirmStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/UxWithCourtesyContactListStrategy.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/KoErrorStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendAddSercqPecStartActivationStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendAddSercqSendAddEmailStartStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendAddSercqSendAddSmsStartStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendAddSercqSendEnterFlowStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendAddSercqSendUxConversionStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/SendAddSercqSendUxSuccessStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/UxConfirmStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/Strategies/__test__/UxWithCourtesyContactListStrategy.test.ts
  packages/pn-personafisica-webapp/src/utility/MixpanelUtils/__test__/PFEventStrategyFactory.test.ts
  packages/pn-personafisica-webapp/src/utility/mixpanel.ts
Labels: TECH-TRACK-SERCQ-25
